### ISSUE TITLE
isOver being falsely set on DropTarget

### ISSUE THREAD

**Issue by AmanMinhas** [zyzo/react-dnd-mouse-backend#10]
[GIF](https://gyazo.com/9ca3652713ffab789e6d2fc0c3426cc7)

As you can see in the GIF above, isOver is randomly being set to true even when it should not.

More details: 
[StackOverflow](https://stackoverflow.com/questions/48794748/react-dnd-drop-firing-twice?noredirect=1#comment84601299_48794748)

**Comment by zyzo** [comment]
Did not reproduce
