### ISSUE TITLE
isOver does not work correctly for nested drop targets

### ISSUE THREAD

**Issue by vanmeegen** [zyzo/react-dnd-mouse-backend#13]
in react-dnd DragDropMonitorImpl.js 
function isOverTarget expects the target ids to be sorted by their containment, leave last in the list:
```
var index = targetIds.indexOf(targetId);
        if (shallow) {
            return index === targetIds.length - 1;
        }
        else {
            return index > -1;
        }
```
Thus MouseBackend.js handleWindowMoveCapture should sort the target ids by their containment relationship to support correct nesting so that isOver(shallow) returns true for the most nested element.

**Comment by zyzo** [comment]
Your proposed solution https://github.com/vanmeegen/react-dnd-mouse-backend/commit/92aeedb7346e7f90f0307b7b23124f3b0e004789 seems to miss the case of overlapping elements (see example [here](http://zyzo.github.io/react-dnd-mouse-backend/?selectedKind=Advanced&selectedStory=Nested%20%2F%20Overlapping%20Targets&full=0&addons=0&stories=1&panelRight=0)).

[react-dnd-touch-backend](https://github.com/yahoo/react-dnd-touch-backend) seems to provide a way to override how the target ids are calculated (using getDropTargetElementsAtPoint function), maybe it's a good idea. In the meantime, drop targets can still be "sorted" using their order of insertion in the DOM (there are maybe cases where this can't be achieved, would love to discuss).
