### ISSUE TITLE
how to use  connectDragPreview?

### ISSUE THREAD

**Issue by wait-hua** [zyzo/react-dnd-mouse-backend#19]

**Comment by zyzo** [comment]
`connectDragPreview` seems to use [DataTransfer.setDragImage](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage) which is for html backend only.

For mouse backend please refer to this example:
[demo](http://zyzo.github.io/react-dnd-mouse-backend/?selectedKind=With%20Drag%20Preview&selectedStory=Custom%20Drag%20Preview&full=0&addons=0&stories=1&panelRight=0)
[code](https://github.com/zyzo/react-dnd-mouse-backend/blob/master/example/src/WithDragPreview/DragPreview.js)
