### ISSUE TITLE
Handler prevents default on everything on the page

### ISSUE THREAD

**Issue by dpiatek** [zyzo/react-dnd-mouse-backend#2]
Hi @zyzo . First of all thanks for this backend - it's been very useful. There is a serious bug though. The `preventDefault` here https://github.com/zyzo/react-dnd-mouse-backend/blob/master/src/MouseBackend.js#L138 is executed on every `mousedown` on the page, so it's preventing the default behaviour on buttons, textareas and other elements. Some of them will work because there will be a `click` event also fired.

The fix would be to remove that preventDefault but my question is why is it there in the first place? If it's needed could not be replaced by `isDragging` check?

**Comment by zyzo** [comment]
Hi, 
I added it because of a bug causing `move` event to behave incorrectly. But the fix was suboptimal that's for sure. I'll do smt about it. Thanks for the report !
